# Generated by Django 4.1.1 on 2022-09-21 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('create_date', models.DateField(verbose_name='Create date')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellidos')),
                ('correo', models.EmailField(max_length=100, verbose_name='correo')),
                ('telefono', models.CharField(max_length=30, verbose_name='telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_auxiliar', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registro_auxiliar_enfermero', to='authApp.auxiliar')),
                ('id_usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_enfermero', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('relacion', models.CharField(max_length=20)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_auxiliar_registro_familiar', to='authApp.auxiliar')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_familiar', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id_historia_c', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.TextField(max_length=2000, null=True)),
                ('entorno', models.CharField(max_length=20, null=True)),
                ('sugerencias', models.TextField(max_length=2000, null=True)),
                ('id_enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_historia_enfermero', to='authApp.enfermero')),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_historia_familiar', to='authApp.familiar')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=15, null=True)),
                ('registrodos', models.CharField(max_length=15, null=True)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_auxiliar_registro_medico', to='authApp.auxiliar')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_medico', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(verbose_name='create_date')),
                ('direccion', models.CharField(max_length=50, verbose_name='residencia')),
                ('ciudad', models.CharField(max_length=20, verbose_name='ciudad')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente_medico', to='authApp.medico')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_auxiliar_registro_paciente', to='authApp.auxiliar')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_paciente', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signos',
            fields=[
                ('id_signos_vitales', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=20, null=True)),
                ('frecuencia_respiratoria', models.CharField(max_length=20, null=True)),
                ('frecuencia_cardiaca', models.CharField(max_length=20, null=True)),
                ('temperatura', models.CharField(max_length=20, null=True)),
                ('presion_arterial', models.CharField(max_length=20, null=True)),
                ('glicemias', models.CharField(max_length=20, null=True)),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_familiar_signos', to='authApp.familiar')),
                ('id_historias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_signos_historia', to='authApp.historia')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente_signos', to='authApp.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='historia',
            name='id_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_historia_medico', to='authApp.medico'),
        ),
        migrations.AddField(
            model_name='historia',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_historia_paciente', to='authApp.paciente'),
        ),
    ]
