# Generated by Django 4.1.1 on 2022-09-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='registrodos',
            new_name='registro',
        ),
    ]
